fix: fix missing workspace_id argument in TFC vars update command
Command was failing with this error:
"TypeError: update() missing 1 required positional argument: 'workspace_id'"
Workspace id has been added to the 'api.workspace_vars.update' call